install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore src\Elision.Foundation.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
 build_script:
  - cmd: msbuild src\Elision.Foundation.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:normal /p:PackageVersion=%GitVersion_SemVer%