using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
