using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision {
	public partial struct Templates {
	    public struct ThemeEmbeddedResource
		{
			public static readonly ID TemplateId = new ID("{06234046-5BC2-4457-87C2-6B09EBB797D3}");
			public const string Name = "ThemeEmbeddedResource";
            public struct FieldIds {                public static readonly ID ResourceCode = new ID("{1E0ED541-79D4-43C7-930E-2BED12B23B63}");                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");			}

			public struct FieldNames
            {                public const string ResourceCode = "ResourceCode";                public const string PageModes = "PageModes";                public const string ResourceLocation = "ResourceLocation";                public const string SupportedDevices = "SupportedDevices";		    }
		}
    }
}
namespace Elision
{
    public partial struct Renderings {
        public partial struct Themes
        {
            public static readonly ID BodyBottomResources = new ID("{081E0D0C-D55F-42A1-A5D7-A9F3A975153C}");
        }
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct Theme
		{
			public static readonly ID TemplateId = new ID("{121B5A57-E9E8-4429-A41D-811CA98116E1}");
			public const string Name = "Theme";
            public struct FieldIds {                public static readonly ID MvcAreaName = new ID("{0BE49B84-3F8C-48D9-93A5-770604D78323}");			}

			public struct FieldNames
            {                public const string MvcAreaName = "MvcAreaName";		    }
		}
    }
}
namespace Elision
{
    public partial struct Renderings {
        public partial struct Themes
        {
            public static readonly ID BodyTopResources = new ID("{176AC3B8-2AA5-4811-8BD3-FAA212881824}");
        }
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct Template_Field
		{
			public static readonly ID TemplateId = new ID("{455A3E98-A627-4B40-8035-E683A0331AC7}");
			public const string Name = "Template field";
            public struct FieldIds {                public static readonly ID HideWithStandardFields = new ID("{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}");			}

			public struct FieldNames
            {                public const string HideWithStandardFields = "HideWithStandardFields";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct ResponsiveImageProfile
		{
			public static readonly ID TemplateId = new ID("{782B9364-9641-4353-9AFE-BCF5E0E44B6C}");
			public const string Name = "ResponsiveImageProfile";
            public struct FieldIds {                public static readonly ID DefaultImageSize = new ID("{964D48DE-984E-4108-B490-5942832DFBEA}");			}

			public struct FieldNames
            {                public const string DefaultImageSize = "DefaultImageSize";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _ColorScheme
		{
			public static readonly ID TemplateId = new ID("{7CBBB87E-7EA0-4BF6-AE5D-EE0437722BF0}");
			public const string Name = "_ColorScheme";
            public struct FieldIds {                public static readonly ID ColorScheme = new ID("{35B7B14B-F1B2-4D06-95AD-B696917D26E5}");			}

			public struct FieldNames
            {                public const string ColorScheme = "ColorScheme";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _Themable
		{
			public static readonly ID TemplateId = new ID("{7D0DCCF0-891D-4A14-9B1D-2251DF4B0FB7}");
			public const string Name = "_Themable";
            public struct FieldIds {                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");			}

			public struct FieldNames
            {                public const string Theme = "Theme";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct ThemeLinkedResource
		{
			public static readonly ID TemplateId = new ID("{9D560638-C289-4C6F-ADF2-06760928ED55}");
			public const string Name = "ThemeLinkedResource";
            public struct FieldIds {                public static readonly ID ResourceLink = new ID("{11B3B1A5-59F9-4EC2-A0DA-A1A6DAF1B944}");                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");			}

			public struct FieldNames
            {                public const string ResourceLink = "ResourceLink";                public const string PageModes = "PageModes";                public const string ResourceLocation = "ResourceLocation";                public const string SupportedDevices = "SupportedDevices";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct ColorScheme
		{
			public static readonly ID TemplateId = new ID("{9F59984F-0638-4664-89D8-07B021D4D5A4}");
			public const string Name = "ColorScheme";
            public struct FieldIds {                public static readonly ID BackgroundColor = new ID("{503D6314-7B28-455B-AB54-E9D894479321}");                public static readonly ID ForegroundColor = new ID("{91B68421-350B-4365-987B-AA2C45A902F6}");			}

			public struct FieldNames
            {                public const string BackgroundColor = "BackgroundColor";                public const string ForegroundColor = "ForegroundColor";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _SiteScripts
		{
			public static readonly ID TemplateId = new ID("{A05913A9-FC8E-4E05-9741-61E480885E91}");
			public const string Name = "_SiteScripts";
            public struct FieldIds {                public static readonly ID SiteBodyTopScript = new ID("{F21C2621-329A-4D5A-AAC1-475DA8CE8954}");                public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");                public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");			}

			public struct FieldNames
            {                public const string SiteBodyTopScript = "SiteBodyTopScript";                public const string SiteFootScript = "SiteFootScript";                public const string SiteHeadScript = "SiteHeadScript";		    }
		}
    }
}
namespace Elision
{
    public partial struct Renderings {
        public partial struct Themes
        {
            public static readonly ID HeadResources = new ID("{A1F97BCC-0F5A-4A9B-AA67-0F22E23268AA}");
        }
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct RenderingFolderWithArea
		{
			public static readonly ID TemplateId = new ID("{ACC5FB47-950F-45FA-A6A7-15C1C681CBA7}");
			public const string Name = "RenderingFolderWithArea";
            public struct FieldIds {                public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");			}

			public struct FieldNames
            {                public const string AreaName = "AreaName";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct ResponsiveImageSize
		{
			public static readonly ID TemplateId = new ID("{AF7849FC-069E-4EC1-82FF-065AC40C9DF3}");
			public const string Name = "ResponsiveImageSize";
            public struct FieldIds {                public static readonly ID ImageWidth = new ID("{2D396085-0373-45E0-AD3F-10D5676D7367}");                public static readonly ID WindowMinWidth = new ID("{A0819F72-60D2-41B7-8F7D-E1955BEB22AF}");			}

			public struct FieldNames
            {                public const string ImageWidth = "ImageWidth";                public const string WindowMinWidth = "WindowMinWidth";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct ResourceLocation
		{
			public static readonly ID TemplateId = new ID("{BA528F98-A18C-405D-A94C-DA68E4B433F8}");
			public const string Name = "ResourceLocation";
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct MvcAreaName
		{
			public static readonly ID TemplateId = new ID("{BD57D269-42CE-416C-8B18-C7E3733DA626}");
			public const string Name = "MvcAreaName";
            public struct FieldIds {                public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");			}

			public struct FieldNames
            {                public const string AreaName = "AreaName";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _ThemeResource
		{
			public static readonly ID TemplateId = new ID("{D522F52B-09DF-442D-84A9-17A497C00BCC}");
			public const string Name = "_ThemeResource";
            public struct FieldIds {                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");			}

			public struct FieldNames
            {                public const string PageModes = "PageModes";                public const string ResourceLocation = "ResourceLocation";                public const string SupportedDevices = "SupportedDevices";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _ContentPage
		{
			public static readonly ID TemplateId = new ID("{D5950FBE-F4A5-45CB-BD88-6EE0B8BEEC54}");
			public const string Name = "_ContentPage";
            public struct FieldIds {                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");			}

			public struct FieldNames
            {                public const string PageBodyTopScript = "PageBodyTopScript";                public const string PageFootScript = "PageFootScript";                public const string PageHeadScript = "PageHeadScript";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _PageScripts
		{
			public static readonly ID TemplateId = new ID("{DB1E7728-506A-4D2F-A9F7-9172692D4A71}");
			public const string Name = "_PageScripts";
            public struct FieldIds {                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");			}

			public struct FieldNames
            {                public const string PageBodyTopScript = "PageBodyTopScript";                public const string PageFootScript = "PageFootScript";                public const string PageHeadScript = "PageHeadScript";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct Website
		{
			public static readonly ID TemplateId = new ID("{E87C2B17-E271-4DD2-AAA7-6CDD3D39FD0A}");
			public const string Name = "Website";
            public struct FieldIds {                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");			}

			public struct FieldNames
            {                public const string Theme = "Theme";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct _HomePage
		{
			public static readonly ID TemplateId = new ID("{E9B6FBA3-AF11-429B-9709-CEDD0087E57D}");
			public const string Name = "_HomePage";
            public struct FieldIds {                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");                public static readonly ID SiteBodyTopScript = new ID("{F21C2621-329A-4D5A-AAC1-475DA8CE8954}");                public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");                public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");			}

			public struct FieldNames
            {                public const string PageBodyTopScript = "PageBodyTopScript";                public const string PageFootScript = "PageFootScript";                public const string PageHeadScript = "PageHeadScript";                public const string SiteBodyTopScript = "SiteBodyTopScript";                public const string SiteFootScript = "SiteFootScript";                public const string SiteHeadScript = "SiteHeadScript";                public const string Theme = "Theme";		    }
		}
    }
}
namespace Elision {
	public partial struct Templates {
	    public struct PageMode
		{
			public static readonly ID TemplateId = new ID("{F2260259-BCEC-462A-BD5E-F9E5D66E1A9F}");
			public const string Name = "PageMode";
		}
    }
}
