using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
// ReSharper disable InconsistentNaming
// ReSharper disable MemberHidesStaticFromOuterClass
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{06234046-5BC2-4457-87C2-6B09EBB797D3}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeEmbeddedResource</description></item>
        /// </list>
        /// </summary>
        public struct ThemeEmbeddedResource
        {
            public static readonly ID TemplateId = new ID("{06234046-5BC2-4457-87C2-6B09EBB797D3}");
            public const string Name = "ThemeEmbeddedResource";

            public struct FieldIds
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{1E0ED541-79D4-43C7-930E-2BED12B23B63}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeEmbeddedResource/Resource/ResourceCode</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ResourceCode = new ID("{1E0ED541-79D4-43C7-930E-2BED12B23B63}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageModes = "PageModes";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{1E0ED541-79D4-43C7-930E-2BED12B23B63}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeEmbeddedResource/Resource/ResourceCode</description></item>
                /// </list>
                /// </summary>
                public const string ResourceCode = "ResourceCode";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string ResourceLocation = "ResourceLocation";
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string SupportedDevices = "SupportedDevices";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct Renderings
    {
        public partial struct Themes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{081E0D0C-D55F-42A1-A5D7-A9F3A975153C}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Elision/Themes/BodyBottomResources</description></item>
            /// </list>
            /// </summary>
            public static readonly ID BodyBottomResources = new ID("{081E0D0C-D55F-42A1-A5D7-A9F3A975153C}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{0D0F86CC-EFE2-47D0-9605-54A38BC70729}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Get Lookup Source Items/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Get_Lookup_Source_Items = new ID("{0D0F86CC-EFE2-47D0-9605-54A38BC70729}");
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{121B5A57-E9E8-4429-A41D-811CA98116E1}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/Theme</description></item>
        /// </list>
        /// </summary>
        public struct Theme
        {
            public static readonly ID TemplateId = new ID("{121B5A57-E9E8-4429-A41D-811CA98116E1}");
            public const string Name = "Theme";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{0BE49B84-3F8C-48D9-93A5-770604D78323}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/Theme/Data/MvcAreaName</description></item>
                /// </list>
                /// </summary>
                public static readonly ID MvcAreaName = new ID("{0BE49B84-3F8C-48D9-93A5-770604D78323}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{0BE49B84-3F8C-48D9-93A5-770604D78323}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/Theme/Data/MvcAreaName</description></item>
                /// </list>
                /// </summary>
                public const string MvcAreaName = "MvcAreaName";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{122AE27A-D84F-4C5E-8367-0F42C764976E}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Folders/ComponentsFolder</description></item>
        /// </list>
        /// </summary>
        public struct ComponentsFolder
        {
            public static readonly ID TemplateId = new ID("{122AE27A-D84F-4C5E-8367-0F42C764976E}");
            public const string Name = "ComponentsFolder";

		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct Renderings
    {
        public partial struct Themes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{176AC3B8-2AA5-4811-8BD3-FAA212881824}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Elision/Themes/BodyTopResources</description></item>
            /// </list>
            /// </summary>
            public static readonly ID BodyTopResources = new ID("{176AC3B8-2AA5-4811-8BD3-FAA212881824}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{1D38B82B-6CFD-4F8F-8745-5364DA58107E}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Placeholder Settings/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Placeholder_Settings = new ID("{1D38B82B-6CFD-4F8F-8745-5364DA58107E}");
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct ResourceLocations
        {
            /// <summary>
            /// The Body Top option.
            /// <list type="table">
            ///     <item><term>ID:</term><description>{252C91F0-B1CA-4F31-ABD4-A9505C180983}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/ResourceLocations/Body Top</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Body_Top = new ID("{252C91F0-B1CA-4F31-ABD4-A9505C180983}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// The Template field template.
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{455A3E98-A627-4B40-8035-E683A0331AC7}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/System/Templates/Template field</description></item>
        /// </list>
        /// </summary>
        public struct Template_Field
        {
            public static readonly ID TemplateId = new ID("{455A3E98-A627-4B40-8035-E683A0331AC7}");
            public const string Name = "Template field";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/System/Templates/Template field/Data/HideWithStandardFields</description></item>
                /// </list>
                /// </summary>
                public static readonly ID HideWithStandardFields = new ID("{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Checkbox</description></item>
                ///     <item><term>Field ID:</term><description>{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/System/Templates/Template field/Data/HideWithStandardFields</description></item>
                /// </list>
                /// </summary>
                public const string HideWithStandardFields = "HideWithStandardFields";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{47E07926-BF3A-4C60-A586-AD615023D62B}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Get Compatible Renderings/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Get_Compatible_Renderings = new ID("{47E07926-BF3A-4C60-A586-AD615023D62B}");
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{71FF2442-3688-481C-867E-47F940F0A6CE}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Get Rendering Datasource/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Get_Rendering_Datasource = new ID("{71FF2442-3688-481C-867E-47F940F0A6CE}");
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{782B9364-9641-4353-9AFE-BCF5E0E44B6C}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageProfile</description></item>
        /// </list>
        /// </summary>
        public struct ResponsiveImageProfile
        {
            public static readonly ID TemplateId = new ID("{782B9364-9641-4353-9AFE-BCF5E0E44B6C}");
            public const string Name = "ResponsiveImageProfile";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{964D48DE-984E-4108-B490-5942832DFBEA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageProfile/Responsive Image Profile/DefaultImageSize</description></item>
                /// </list>
                /// </summary>
                public static readonly ID DefaultImageSize = new ID("{964D48DE-984E-4108-B490-5942832DFBEA}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{964D48DE-984E-4108-B490-5942832DFBEA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageProfile/Responsive Image Profile/DefaultImageSize</description></item>
                /// </list>
                /// </summary>
                public const string DefaultImageSize = "DefaultImageSize";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct RulesFolders
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>ID:</term><description>{7C5815EB-7E4C-47C4-8224-C68BBC543270}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/system/Settings/Rules/Replace Rendering/Rules</description></item>
        /// </list>
        /// </summary>
        public static readonly ID Replace_Rendering = new ID("{7C5815EB-7E4C-47C4-8224-C68BBC543270}");
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{7CBBB87E-7EA0-4BF6-AE5D-EE0437722BF0}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_ColorScheme</description></item>
        /// </list>
        /// </summary>
        public struct _ColorScheme
        {
            public static readonly ID TemplateId = new ID("{7CBBB87E-7EA0-4BF6-AE5D-EE0437722BF0}");
            public const string Name = "_ColorScheme";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{35B7B14B-F1B2-4D06-95AD-B696917D26E5}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_ColorScheme/Color Scheme/ColorScheme</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ColorScheme = new ID("{35B7B14B-F1B2-4D06-95AD-B696917D26E5}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{35B7B14B-F1B2-4D06-95AD-B696917D26E5}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_ColorScheme/Color Scheme/ColorScheme</description></item>
                /// </list>
                /// </summary>
                public const string ColorScheme = "ColorScheme";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{7D0DCCF0-891D-4A14-9B1D-2251DF4B0FB7}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable</description></item>
        /// </list>
        /// </summary>
        public struct _Themable
        {
            public static readonly ID TemplateId = new ID("{7D0DCCF0-891D-4A14-9B1D-2251DF4B0FB7}");
            public const string Name = "_Themable";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// </summary>
                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// </summary>
                public const string Theme = "Theme";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{9D560638-C289-4C6F-ADF2-06760928ED55}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeLinkedResource</description></item>
        /// </list>
        /// </summary>
        public struct ThemeLinkedResource
        {
            public static readonly ID TemplateId = new ID("{9D560638-C289-4C6F-ADF2-06760928ED55}");
            public const string Name = "ThemeLinkedResource";

            public struct FieldIds
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>General Link</description></item>
                ///     <item><term>Field ID:</term><description>{11B3B1A5-59F9-4EC2-A0DA-A1A6DAF1B944}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeLinkedResource/Resource/ResourceLink</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ResourceLink = new ID("{11B3B1A5-59F9-4EC2-A0DA-A1A6DAF1B944}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageModes = "PageModes";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>General Link</description></item>
                ///     <item><term>Field ID:</term><description>{11B3B1A5-59F9-4EC2-A0DA-A1A6DAF1B944}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ThemeLinkedResource/Resource/ResourceLink</description></item>
                /// </list>
                /// </summary>
                public const string ResourceLink = "ResourceLink";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string ResourceLocation = "ResourceLocation";
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string SupportedDevices = "SupportedDevices";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{9F59984F-0638-4664-89D8-07B021D4D5A4}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ColorScheme</description></item>
        /// </list>
        /// </summary>
        public struct ColorScheme
        {
            public static readonly ID TemplateId = new ID("{9F59984F-0638-4664-89D8-07B021D4D5A4}");
            public const string Name = "ColorScheme";

            public struct FieldIds
            {
                /// <summary>
                /// <para>Ex: #60676b</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{503D6314-7B28-455B-AB54-E9D894479321}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ColorScheme/Design/BackgroundColor</description></item>
                /// </list>
                /// </summary>
                public static readonly ID BackgroundColor = new ID("{503D6314-7B28-455B-AB54-E9D894479321}");
                /// <summary>
                /// <para>Ex: #60676b</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{91B68421-350B-4365-987B-AA2C45A902F6}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ColorScheme/Design/ForegroundColor</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ForegroundColor = new ID("{91B68421-350B-4365-987B-AA2C45A902F6}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>Ex: #60676b</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{503D6314-7B28-455B-AB54-E9D894479321}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ColorScheme/Design/BackgroundColor</description></item>
                /// </list>
                /// </summary>
                public const string BackgroundColor = "BackgroundColor";
                /// <summary>
                /// <para>Ex: #60676b</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{91B68421-350B-4365-987B-AA2C45A902F6}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ColorScheme/Design/ForegroundColor</description></item>
                /// </list>
                /// </summary>
                public const string ForegroundColor = "ForegroundColor";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{A05913A9-FC8E-4E05-9741-61E480885E91}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts</description></item>
        /// </list>
        /// </summary>
        public struct _SiteScripts
        {
            public static readonly ID TemplateId = new ID("{A05913A9-FC8E-4E05-9741-61E480885E91}");
            public const string Name = "_SiteScripts";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F21C2621-329A-4D5A-AAC1-475DA8CE8954}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteBodyTopScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID SiteBodyTopScript = new ID("{F21C2621-329A-4D5A-AAC1-475DA8CE8954}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{52E994D5-E743-4DD6-9B86-60C7D170ED72}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteFootScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{332BEBEB-F4E8-4078-A9CE-F718E69EC974}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteHeadScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F21C2621-329A-4D5A-AAC1-475DA8CE8954}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteBodyTopScript</description></item>
                /// </list>
                /// </summary>
                public const string SiteBodyTopScript = "SiteBodyTopScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{52E994D5-E743-4DD6-9B86-60C7D170ED72}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteFootScript</description></item>
                /// </list>
                /// </summary>
                public const string SiteFootScript = "SiteFootScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{332BEBEB-F4E8-4078-A9CE-F718E69EC974}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteHeadScript</description></item>
                /// </list>
                /// </summary>
                public const string SiteHeadScript = "SiteHeadScript";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct Renderings
    {
        public partial struct Themes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>Rendering ID:</term><description>{A1F97BCC-0F5A-4A9B-AA67-0F22E23268AA}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/layout/Renderings/Elision/Themes/HeadResources</description></item>
            /// </list>
            /// </summary>
            public static readonly ID HeadResources = new ID("{A1F97BCC-0F5A-4A9B-AA67-0F22E23268AA}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct PageModes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>ID:</term><description>{A870FE50-E507-43B1-AE62-09AFBE545990}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/PageModes/IsPreview</description></item>
            /// </list>
            /// </summary>
            public static readonly ID IsPreview = new ID("{A870FE50-E507-43B1-AE62-09AFBE545990}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{ACC5FB47-950F-45FA-A6A7-15C1C681CBA7}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/RenderingFolderWithArea</description></item>
        /// </list>
        /// </summary>
        public struct RenderingFolderWithArea
        {
            public static readonly ID TemplateId = new ID("{ACC5FB47-950F-45FA-A6A7-15C1C681CBA7}");
            public const string Name = "RenderingFolderWithArea";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/MvcAreaName/Routing/AreaName</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/MvcAreaName/Routing/AreaName</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string AreaName = "AreaName";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{AF7849FC-069E-4EC1-82FF-065AC40C9DF3}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageSize</description></item>
        /// </list>
        /// </summary>
        public struct ResponsiveImageSize
        {
            public static readonly ID TemplateId = new ID("{AF7849FC-069E-4EC1-82FF-065AC40C9DF3}");
            public const string Name = "ResponsiveImageSize";

            public struct FieldIds
            {
                /// <summary>
                /// <para>in pixels, e.g. 300. Use 0 for uploaded image size</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Number</description></item>
                ///     <item><term>Field ID:</term><description>{2D396085-0373-45E0-AD3F-10D5676D7367}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageSize/Responsive Image Size/ImageWidth</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ImageWidth = new ID("{2D396085-0373-45E0-AD3F-10D5676D7367}");
                /// <summary>
                /// <para>must specify unit of measure, e.g. 500px</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A0819F72-60D2-41B7-8F7D-E1955BEB22AF}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageSize/Responsive Image Size/WindowMinWidth</description></item>
                /// </list>
                /// </summary>
                public static readonly ID WindowMinWidth = new ID("{A0819F72-60D2-41B7-8F7D-E1955BEB22AF}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>in pixels, e.g. 300. Use 0 for uploaded image size</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Number</description></item>
                ///     <item><term>Field ID:</term><description>{2D396085-0373-45E0-AD3F-10D5676D7367}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageSize/Responsive Image Size/ImageWidth</description></item>
                /// </list>
                /// </summary>
                public const string ImageWidth = "ImageWidth";
                /// <summary>
                /// <para>must specify unit of measure, e.g. 500px</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A0819F72-60D2-41B7-8F7D-E1955BEB22AF}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResponsiveImageSize/Responsive Image Size/WindowMinWidth</description></item>
                /// </list>
                /// </summary>
                public const string WindowMinWidth = "WindowMinWidth";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{BA528F98-A18C-405D-A94C-DA68E4B433F8}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/ResourceLocation</description></item>
        /// </list>
        /// </summary>
        public struct ResourceLocation
        {
            public static readonly ID TemplateId = new ID("{BA528F98-A18C-405D-A94C-DA68E4B433F8}");
            public const string Name = "ResourceLocation";

		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{BD57D269-42CE-416C-8B18-C7E3733DA626}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/MvcAreaName</description></item>
        /// </list>
        /// </summary>
        public struct MvcAreaName
        {
            public static readonly ID TemplateId = new ID("{BD57D269-42CE-416C-8B18-C7E3733DA626}");
            public const string Name = "MvcAreaName";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/MvcAreaName/Routing/AreaName</description></item>
                /// </list>
                /// </summary>
                public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Single-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/System/Layout/MvcAreaName/Routing/AreaName</description></item>
                /// </list>
                /// </summary>
                public const string AreaName = "AreaName";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{D522F52B-09DF-442D-84A9-17A497C00BCC}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource</description></item>
        /// </list>
        /// </summary>
        public struct _ThemeResource
        {
            public static readonly ID TemplateId = new ID("{D522F52B-09DF-442D-84A9-17A497C00BCC}");
            public const string Name = "_ThemeResource";

            public struct FieldIds
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// </summary>
                public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// </summary>
                public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// </summary>
                public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <para>leave blank for all page modes</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{B7100C64-8316-44E7-926D-9F2FE164CD69}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/PageModes</description></item>
                /// </list>
                /// </summary>
                public const string PageModes = "PageModes";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/ResourceLocation</description></item>
                /// </list>
                /// </summary>
                public const string ResourceLocation = "ResourceLocation";
                /// <summary>
                /// <para>leave blank for all devices</para>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multilist</description></item>
                ///     <item><term>Field ID:</term><description>{70AA35E0-E88C-4504-A512-58BBB4D10AAA}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/_ThemeResource/Resource/SupportedDevices</description></item>
                /// </list>
                /// </summary>
                public const string SupportedDevices = "SupportedDevices";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{D5950FBE-F4A5-45CB-BD88-6EE0B8BEEC54}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Content/_ContentPage</description></item>
        /// </list>
        /// </summary>
        public struct _ContentPage
        {
            public static readonly ID TemplateId = new ID("{D5950FBE-F4A5-45CB-BD88-6EE0B8BEEC54}");
            public const string Name = "_ContentPage";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageBodyTopScript = "PageBodyTopScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageFootScript = "PageFootScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageHeadScript = "PageHeadScript";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct ResourceLocations
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>ID:</term><description>{D5B9F2D9-A049-42A5-9B5E-9ED81C70CD7B}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/ResourceLocations/Head</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Head = new ID("{D5B9F2D9-A049-42A5-9B5E-9ED81C70CD7B}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{DB1E7728-506A-4D2F-A9F7-9172692D4A71}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts</description></item>
        /// </list>
        /// </summary>
        public struct _PageScripts
        {
            public static readonly ID TemplateId = new ID("{DB1E7728-506A-4D2F-A9F7-9172692D4A71}");
            public const string Name = "_PageScripts";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// </summary>
                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// </summary>
                public const string PageBodyTopScript = "PageBodyTopScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// </summary>
                public const string PageFootScript = "PageFootScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// </summary>
                public const string PageHeadScript = "PageHeadScript";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{E87C2B17-E271-4DD2-AAA7-6CDD3D39FD0A}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Content/Website</description></item>
        /// </list>
        /// </summary>
        public struct Website
        {
            public static readonly ID TemplateId = new ID("{E87C2B17-E271-4DD2-AAA7-6CDD3D39FD0A}");
            public const string Name = "Website";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string Theme = "Theme";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{E9B6FBA3-AF11-429B-9709-CEDD0087E57D}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Content/_HomePage</description></item>
        /// </list>
        /// </summary>
        public struct _HomePage
        {
            public static readonly ID TemplateId = new ID("{E9B6FBA3-AF11-429B-9709-CEDD0087E57D}");
            public const string Name = "_HomePage";

            public struct FieldIds
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageBodyTopScript = new ID("{451F49E1-52E1-4622-B113-20970AAAABAC}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F21C2621-329A-4D5A-AAC1-475DA8CE8954}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID SiteBodyTopScript = new ID("{F21C2621-329A-4D5A-AAC1-475DA8CE8954}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{52E994D5-E743-4DD6-9B86-60C7D170ED72}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{332BEBEB-F4E8-4078-A9CE-F718E69EC974}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
            }

            public struct FieldNames
            {
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{451F49E1-52E1-4622-B113-20970AAAABAC}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageBodyTopScript = "PageBodyTopScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageFootScript = "PageFootScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_PageScripts/Scripts/PageHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string PageHeadScript = "PageHeadScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{F21C2621-329A-4D5A-AAC1-475DA8CE8954}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteBodyTopScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string SiteBodyTopScript = "SiteBodyTopScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{52E994D5-E743-4DD6-9B86-60C7D170ED72}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteFootScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string SiteFootScript = "SiteFootScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Multi-Line Text</description></item>
                ///     <item><term>Field ID:</term><description>{332BEBEB-F4E8-4078-A9CE-F718E69EC974}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_SiteScripts/Scripts/SiteHeadScript</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string SiteHeadScript = "SiteHeadScript";
                /// <summary>
                /// <list type="table">
                ///     <item><term>Field Type:</term><description>Droplink</description></item>
                ///     <item><term>Field ID:</term><description>{F318342F-A549-47F7-BD88-25086B46B9D9}</description></item>
                ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/_Base/_Themable/Theme/Theme</description></item>
                /// </list>
                /// <para>This is an inherited template field</para>
                /// </summary>
                public const string Theme = "Theme";
            }
		}
    }
}
namespace Elision.Foundation.Kernel
{
	public partial struct Templates
    {
        /// <summary>
        /// <list type="table">
        ///     <item><term>Template ID:</term><description>{F2260259-BCEC-462A-BD5E-F9E5D66E1A9F}</description></item>
        ///     <item><term>Path:</term><description>/sitecore/templates/Elision/Themes/Settings/PageMode</description></item>
        /// </list>
        /// </summary>
        public struct PageMode
        {
            public static readonly ID TemplateId = new ID("{F2260259-BCEC-462A-BD5E-F9E5D66E1A9F}");
            public const string Name = "PageMode";

		}
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct PageModes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>ID:</term><description>{F2BB4AC1-2466-4417-A31F-C7C9F2623468}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/PageModes/IsPageEditorEditing</description></item>
            /// </list>
            /// </summary>
            public static readonly ID IsPageEditorEditing = new ID("{F2BB4AC1-2466-4417-A31F-C7C9F2623468}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct ResourceLocations
        {
            /// <summary>
            /// The Body Bottom option.
            /// <list type="table">
            ///     <item><term>ID:</term><description>{FC8390D8-66F0-4C6F-AC76-B91D9FD8BAC3}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/ResourceLocations/Body Bottom</description></item>
            /// </list>
            /// </summary>
            public static readonly ID Body_Bottom = new ID("{FC8390D8-66F0-4C6F-AC76-B91D9FD8BAC3}");
        }
    }
}
namespace Elision.Foundation.Kernel
{
    public partial struct OptionLists
    {
        public partial struct PageModes
        {
            /// <summary>
            /// <list type="table">
            ///     <item><term>ID:</term><description>{FF2D9DA6-EA47-4F7C-A826-F33E2409B30E}</description></item>
            ///     <item><term>Path:</term><description>/sitecore/system/Settings/Elision/Option Lists/PageModes/IsNormal</description></item>
            /// </list>
            /// </summary>
            public static readonly ID IsNormal = new ID("{FF2D9DA6-EA47-4F7C-A826-F33E2409B30E}");
        }
    }
}
